### ISSUE TITLE
Elevator Cruising

### ISSUE THREAD

**Issue by Gryph667** [TBMCPlugins/Movecraft-3#1]
Current loaded version of Elevator.Craft has CanCruise set to False.

For Ascend and Descend signs to work, we need CanCruise set to True.

In most cases we'd restrict these to manual clicks, but current redstone tech can create continuous elevator movement. The restriction no longer makes sense.

**Comment by NorbiPeti** [comment]
This issue was moved to TBMCPlugins/PluginConfigs#1
